import Foundation

/// Bundled Terms of Use / Privacy Policy text and acceptance bookkeeping.
/// The text mirrors the hosted versions exactly; bump `currentVersion`
/// whenever the wording changes so previously-agreed users are re-prompted.
enum LegalContent {
    static let currentVersion = "2026-07-02"

    static let termsOfUseURL = URL(string: "https://sites.google.com/view/dominus-terms-of-use/home")!
    static let privacyPolicyURL = URL(string: "https://sites.google.com/view/dominusprivacypolicy/home")!

    static let termsOfUseText = """
    DOMINUS — TERMS OF USE
    Last Updated: July 2, 2026

    These Terms of Use ("Terms") are a legal agreement between you and Ethos Creed, an individual developer ("Developer," "we," "us," or "our"), governing your use of the Dominus mobile application (the "App"). By downloading, installing, or using the App, you agree to be bound by these Terms. If you do not agree, do not download, install, or use the App.

    1. ELIGIBILITY
    The App is intended for users who are at least 17 years old. By using the App, you represent that you are at least 17 years of age. The App is not directed at children, and the Developer does not knowingly permit use by anyone under 17.

    2. LICENSE GRANT
    Subject to your compliance with these Terms and the Usage Rules set forth in the Apple Media Services Terms and Conditions (App Store Terms of Service), the Developer grants you a limited, non-exclusive, non-transferable, revocable license to use the App for your personal, non-commercial purposes on any Apple-branded product that you own or control, as permitted by those Usage Rules.

    3. HOW DOMINUS WORKS / AI-GENERATED CONTENT
    Dominus runs a bundled, on-device AI language model, on-device speech recognition, and on-device speech synthesis. All processing occurs locally on your device; the App does not require an internet connection for its core features, and it does not transmit your conversations, voice recordings, memory data, or profile information to the Developer, Apple, or any third party.

    The bundled language model is Google's Gemma model. Gemma is provided under and subject to the Gemma Terms of Use found at https://ai.google.dev/gemma/terms, which incorporates the Gemma Prohibited Use Policy found at https://ai.google.dev/gemma/prohibited_use_policy. Section 4 (Acceptable Use) below makes that Prohibited Use Policy a binding part of your agreement with the Developer.

    Responses generated by the App are produced by an automated artificial intelligence model that is not filtered or moderated by the Developer in real time. AI-generated responses:
    - may be inaccurate, incomplete, outdated, or misleading;
    - may include content that is offensive, inappropriate, or unsuitable for some audiences, because the App applies no content filtering;
    - do not constitute medical, legal, financial, or professional advice of any kind.

    You are solely responsible for evaluating and deciding whether to rely on, act upon, or share any output produced by the App. Do not use the App as a substitute for professional advice or emergency services.

    4. ACCEPTABLE USE
    By using the App, you agree to comply with Google's Gemma Prohibited Use Policy (https://ai.google.dev/gemma/prohibited_use_policy) as a binding condition of these Terms. Without limiting that policy, you agree not to use the App to:
    - use the App for any unlawful purpose or in violation of any applicable law;
    - infringe, misappropriate, or otherwise violate any individual's or entity's intellectual property or other legal rights;
    - generate or facilitate child sexual abuse material, illegal drug production or distribution, terrorism or violent extremism, malware, or other criminal activity;
    - generate content that promotes hatred, harassment, or bullying, or that facilitates violence, self-harm, or violations of another person's privacy;
    - generate deepfakes, impersonation, false credentials, or other content intended to misinform, mislead, or defame;
    - generate sexually explicit content, including pornography;
    - attempt to override, disable, or circumvent any safety restriction associated with the bundled AI model;
    - attempt to reverse-engineer, decompile, or extract the bundled AI model or other embedded components except as permitted by applicable open-source licenses.

    All such content stays local to your device and is not published, shared, or transmitted by the App itself; violating this section is nonetheless a breach of these Terms and grounds for termination under Section 14.

    5. PRIVACY
    The App is designed so that no personal data, conversation content, voice recordings, or profile information leaves your device. Full details are available in the Dominus Privacy Policy at https://sites.google.com/view/dominusprivacypolicy/home. By using the App, you also agree to the Privacy Policy.

    6. NO WARRANTY
    THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT. THE DEVELOPER DOES NOT WARRANT THAT THE APP WILL BE ERROR-FREE, UNINTERRUPTED, OR THAT ANY AI-GENERATED OUTPUT WILL BE ACCURATE OR APPROPRIATE.
    The App's use of device-level encryption and other security measures reduces, but does not eliminate, the risk of unauthorized access to your data; the Developer makes no warranty that such measures will prevent all possible unauthorized access.

    7. LIMITATION OF LIABILITY
    TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE DEVELOPER BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, PROFITS, OR GOODWILL, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE APP, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE DEVELOPER'S TOTAL LIABILITY FOR ANY CLAIM ARISING FROM THESE TERMS OR THE APP SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE APP, IF ANY, IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.

    8. MAINTENANCE AND SUPPORT
    The Developer is solely responsible for providing any maintenance and support services for the App, to the extent required, if at all, under applicable law. Apple has no obligation whatsoever to furnish any maintenance or support services with respect to the App.

    9. APPLE WARRANTY DISCLAIMER
    In the event of any failure of the App to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the App to you, if any; to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App, and any other claims, losses, liabilities, damages, costs, or expenses attributable to any failure to conform to any warranty will be the Developer's sole responsibility.

    10. PRODUCT CLAIMS
    The Developer, not Apple, is responsible for addressing any claims by you or any third party relating to the App or your possession and/or use of the App, including but not limited to: (i) product liability claims; (ii) any claim that the App fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection, privacy, or similar legislation.

    11. INTELLECTUAL PROPERTY
    The App, including the bundled AI model, source code, and design, is the property of the Developer and its licensors and is protected by intellectual property laws. In the event of any third-party claim that the App or your possession and use of the App infringes that third party's intellectual property rights, the Developer, not Apple, will be solely responsible for the investigation, defense, settlement, and discharge of any such claim.

    12. LEGAL COMPLIANCE / EXPORT
    You represent and warrant that you are not located in a country subject to a U.S. Government embargo or designated by the U.S. Government as a "terrorist supporting" country, and that you are not listed on any U.S. Government list of prohibited or restricted parties.

    13. THIRD-PARTY BENEFICIARY
    You acknowledge and agree that Apple Inc. and its subsidiaries are third-party beneficiaries of these Terms, and that upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third-party beneficiary of these Terms. You acknowledge that this agreement is concluded between you and the Developer only, and not with Apple, and that Apple is not responsible for the App or its content.

    14. TERMINATION
    These Terms remain in effect until terminated by you or the Developer. You may terminate them at any time by deleting the App from your device. The Developer may terminate these Terms if you fail to comply with any provision.

    15. CHANGES TO THESE TERMS
    The Developer may update these Terms from time to time. Material changes will be reflected by an updated "Last Updated" date. Continued use of the App after changes take effect constitutes acceptance of the revised Terms.

    16. GOVERNING LAW
    These Terms are governed by the laws of the State of Arizona, USA, without regard to its conflict-of-law provisions, except where superseded by the applicable Apple Media Services Terms and Conditions.

    17. CONTACT
    Questions about these Terms may be directed to: Ethos Creed, ethoscreed@yahoo.com.
    """

    static let privacyPolicyText = """
    DOMINUS — PRIVACY POLICY
    Last Updated: July 1, 2026

    This Privacy Policy explains how the Dominus mobile application ("Dominus," "the App") handles information. Dominus is developed by Ethos Creed ("Developer," "we," "us").

    THE SHORT VERSION
    Dominus runs entirely on your device. Your conversations, voice recordings, memory data, and profile information are processed and stored locally on your device only. We do not operate any servers for the App, do not collect your data, do not see your data, and cannot transmit it anywhere because the App does not connect to the internet for any of its core features.

    WHAT THE APP ACCESSES, AND WHY
    - Microphone: used only when you activate voice mode, to capture your speech for on-device transcription. Audio is processed on-device and is not recorded to a permanent file or sent anywhere.
    - Speech Recognition: used to convert your speech to text on-device, so the App can respond to you. This does not use any cloud speech API.

    WHAT IS STORED, AND WHERE
    All of the following is stored exclusively in the App's local storage on your device, and is never transmitted off your device by the App:
    - Conversation history (chat messages), stored in a local file in the App's documents directory.
    - Memory Journal entries and current-chat memory, stored in a local on-device database.
    - Profile information you choose to provide (name, role, goals, persona preferences), stored locally in the App's local database and preferences.
    - Audio, voice, and orb display preferences, stored in local device preferences.

    None of this data is uploaded to a server, backed up to iCloud by the App, shared with the Developer, sold, or shared with any third party, because the App has no network functionality for these features.

    DATA SECURITY
    All data stored by the App is encrypted at rest using Apple's built-in Data Protection technology, at the strongest available protection level. This means your conversations, memory journal entries, and profile information are encrypted and inaccessible whenever your device is locked, including to someone in physical possession of your device.

    This protects against unauthorized access from a lost or stolen device. It does not protect against access by someone using your device while it is unlocked, malicious software already running on your device, or disclosure of your device passcode to a third party. No security measure can guarantee absolute protection, and the Developer makes no warranty that these measures will prevent all possible unauthorized access.

    WHAT WE DO NOT DO
    - We do not operate a backend server for the App.
    - We do not use analytics, advertising, or tracking SDKs of any kind.
    - We do not require or support account creation or sign-in.
    - We do not sync your data to iCloud or any other cloud service.
    - We do not sell or share your data, because we never receive it.

    THIRD-PARTY COMPONENTS
    Dominus bundles the following components, which run entirely on-device and do not transmit data anywhere:
    - A locally bundled AI language model, run via an on-device inference engine.
    - An on-device speech-to-text engine.
    - A bundled on-device voice activity detection model, used to detect when you're speaking.
    - Apple's on-device text-to-speech, for spoken responses.

    None of these components send data to the Developer, to their original authors, or to any other party.

    CHILDREN'S PRIVACY
    Dominus is intended for users age 17 and older and is not directed at children. We do not knowingly collect any information from children, and because the App does not collect or transmit data from any user regardless of age, no children's data is collected, stored remotely, or shared.

    YOUR CONTROL OVER YOUR DATA
    Because all data is stored locally:
    - You can delete individual conversations or Memory Journal entries within the App.
    - You can clear your profile information within the App's Profile settings.
    - Deleting the App from your device permanently removes all locally stored conversation, memory, and profile data.

    CHANGES TO THIS POLICY
    We may update this Privacy Policy from time to time. Material changes will be reflected by an updated "Last Updated" date above.

    CONTACT
    Questions about this Privacy Policy may be directed to: Ethos Creed, ethoscreed@yahoo.com.
    """

    static let openSourceLicensesText = """
    DOMINUS — OPEN SOURCE LICENSES & THIRD-PARTY NOTICES
    Last Updated: July 2, 2026

    Dominus is built using the following open-source and third-party components, each of which runs entirely on-device.

    GEMMA
    Dominus bundles Google's Gemma 2 2B IT language model. Gemma is provided under and subject to the Gemma Terms of Use, found at https://ai.google.dev/gemma/terms, which incorporates the Gemma Prohibited Use Policy found at https://ai.google.dev/gemma/prohibited_use_policy. See the Dominus Terms of Use for how these apply to your use of the App.

    WHISPERKIT
    Copyright (c) 2024 argmax, inc.
    Licensed under the MIT License. Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files, to deal in the software without restriction, subject to inclusion of the above copyright notice in all copies or substantial portions of the software. The software is provided "as is," without warranty of any kind.

    LLAMA.CPP
    Copyright (c) 2023-2026 The ggml authors
    Licensed under the MIT License, on the same terms described above.

    SWIFT-LLAMA-CPP
    Copyright (c) 2025 Piotr Gorzelany
    Licensed under the MIT License, on the same terms described above.

    SILERO VAD
    Copyright (c) 2020-present Silero Team
    Licensed under the MIT License, on the same terms described above.

    The full text of the MIT License is available at https://opensource.org/licenses/MIT.
    """
}

/// UserDefaults bookkeeping for first-launch Terms/Privacy acceptance.
enum LegalAcceptance {
    private static let versionKey = "dominus_terms_accepted_version"
    private static let dateKey = "dominus_terms_accepted_date"

    static var hasAcceptedCurrentVersion: Bool {
        UserDefaults.standard.string(forKey: versionKey) == LegalContent.currentVersion
    }

    /// Records acceptance of the current Terms/Privacy version with an
    /// automatic, non-editable timestamp.
    static func recordAcceptance() {
        UserDefaults.standard.set(LegalContent.currentVersion, forKey: versionKey)
        UserDefaults.standard.set(ISO8601DateFormatter().string(from: Date()), forKey: dateKey)
    }

    static var acceptedDate: Date? {
        guard let string = UserDefaults.standard.string(forKey: dateKey) else { return nil }
        return ISO8601DateFormatter().date(from: string)
    }
}
